# Generated by Django 5.0.2 on 2024-03-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_auth',
        ),
    ]
