# Generated by Django 5.0.2 on 2024-03-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authin', '0002_delete_user_auth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_a',
        ),
    ]
