# Generated by Django 5.0.2 on 2024-02-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cardnum',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
