# Generated by Django 5.0.2 on 2024-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_cardnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='famname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(max_length=30),
        ),
    ]
